### PR TITLE
Bug fix: Prevent fatal if class does not exist on Beta Features.

### LINKED ISSUE #198: 6.5.2 Uncaught Error: Class "SCF_Admin_Beta_Feature_Connect_Fields" not found
Description:
After updating to version 6.5.2 of the Secure Custom Fields plugin, a fatal error occurs when accessing the WordPress admin dashboard:

`Uncaught Error: Class "SCF_Admin_Beta_Feature_Connect_Fields" not found
in /wp-content/plugins/secure-custom-fields/includes/admin/beta-features.php on line 50`

`Call stack:

SCF_Admin_Beta_Features::register_beta_feature('SCF_Admin_Beta_Feature_Connect_Fields')
wp-content/plugins/secure-custom-fields/includes/admin/beta-features.php:274
scf_register_admin_beta_feature('SCF_Admin_Beta_Feature_Connect_Fields')
wp-content/plugins/secure-custom-fields/includes/admin/beta-features.php:152
SCF_Admin_Beta_Features::register_beta_features('')
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters('', array)
wp-includes/class-wp-hook.php:348
WP_Hook::do_action(array)
wp-includes/plugin.php:517
do_action('scf/include_admin_beta_features')
wp-content/plugins/secure-custom-fields/includes/admin/beta-features.php:141
SCF_Admin_Beta_Features::include_beta_features()
wp-content/plugins/secure-custom-fields/includes/admin/beta-features.php:75
SCF_Admin_Beta_Features::get_beta_features()
wp-content/plugins/secure-custom-fields/includes/admin/beta-features.php:250
SCF_Admin_Beta_Features::add_beta_features_script('index.php')
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters(NULL, array)
wp-includes/class-wp-hook.php:348
WP_Hook::do_action(array)
wp-includes/plugin.php:517
do_action('admin_enqueue_scripts', 'index.php')
wp-admin/admin-header.php:123
require_once('/home/customer/www/w...min/admin-header.php')
wp-admin/index.php:137`

Additional context:

The error happens immediately when accessing wp-admin/index.php

WordPress version: 6.8.2

PHP version: 8.1

Plugin version: 6.5.2

Environment: Production

Plugin: Secure Custom Fields

Screenshot from Query Monitor attached

Issue:
It seems the class SCF_Admin_Beta_Feature_Connect_Fields is not defined or loaded when it's being registered, causing a fatal error that prevents admin access.

Image

### PR DESCRIPTION
**Pull request by cbravobernal**
Closes #198 and prevents from happening again due to a beta feature trying to load a non existent class.

### CODE REVIEW

File: includes/admin/beta-features.php [hunk 1]
```diff
@@ -47,6 +47,10 @@ public function __construct() {
 		 * @return  void
 		 */
 		public function register_beta_feature( $beta_feature ) {
+			if ( ! class_exists( $beta_feature ) ) {
```
Comment (priethor) [inline includes/admin/beta-features.php:50]: Thanks for adding this safety check 😅
